### ISSUE TITLE
#35 & #57 missing for Achievements

### ISSUE THREAD

**Issue by Ansem717** [jamesmcfadden/overwatch-api#49]
I'm not sure if it's missing or incorrectly typed, but the data for Achievements skips 35 and 57. 

This is why there is only 71 items in the list when counting, but 73 is the highest ID. 

I'm unaware if you're missing #35 & #57 OR if the ID count was incorrectly counted and those numbers were accidentally skipped. 

There could also be a reason for omitting these two numbers, but I may as well just post the issue to bring it to your attention.

**Comment by jamesmcfadden** [comment]
These were probably omitted by accident, but shouldn't pose an issue. That said, fixing may break consumer integrations, so we'll leave as is.

Thanks!
